site_name: ice-learn
site_url: https://example.com/
repo_url: https://github.com/tjyuyao/ice-learn/
site_description: This site is the documentation for ice-learn, yet another high-level deep learning library based on pytorch and pycuda.
site_author: Yuyao Huang
copyright: Copyright (c) 2022 Yuyao Huang

plugins:
    - search
    - awesome-pages

theme:
    name: material
    features:
        - content.code.annotate 

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: true
        # linenums: true
        # linenums_style: pymdownx-inline
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - mdx_math:  # (https://github.com/mitya57/python-markdown-math) 
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']